default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: admin_user
  password: postgres

test:
  <<: *default
  host: localhost
  database: admin_user_test
  password: postgres

docker_test:
  <<: *default
  host: db
  database: admin_user_docker
  password: test1234